-- Chat en tiempo real de TaskForce Global.
-- Ejecutar una sola vez en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  visitor_id uuid not null default auth.uid(),
  name text not null check (char_length(name) between 2 and 80),
  contact text not null check (char_length(contact) between 3 and 120),
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender text not null check (sender in ('client', 'company')),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages(conversation_id, created_at);

alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "visitor reads own conversation" on public.chat_conversations;
create policy "visitor reads own conversation" on public.chat_conversations
for select using (
  visitor_id = auth.uid() or (auth.jwt() ->> 'email') = 'admin@taskforce.uy'
);

drop policy if exists "visitor creates own conversation" on public.chat_conversations;
create policy "visitor creates own conversation" on public.chat_conversations
for insert with check (visitor_id = auth.uid());

drop policy if exists "admin updates conversations" on public.chat_conversations;
create policy "admin updates conversations" on public.chat_conversations
for update using ((auth.jwt() ->> 'email') = 'admin@taskforce.uy')
with check ((auth.jwt() ->> 'email') = 'admin@taskforce.uy');

drop policy if exists "participants read messages" on public.chat_messages;
create policy "participants read messages" on public.chat_messages
for select using (
  exists (
    select 1 from public.chat_conversations c
    where c.id = conversation_id
      and (c.visitor_id = auth.uid() or (auth.jwt() ->> 'email') = 'admin@taskforce.uy')
  )
);

drop policy if exists "participants send messages" on public.chat_messages;
create policy "participants send messages" on public.chat_messages
for insert with check (
  (sender = 'client' and exists (
    select 1 from public.chat_conversations c
    where c.id = conversation_id and c.visitor_id = auth.uid()
  ))
  or
  (sender = 'company' and (auth.jwt() ->> 'email') = 'admin@taskforce.uy')
);

create or replace function public.touch_chat_conversation()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.chat_conversations
  set updated_at = now(),
      status = case when new.sender = 'client' then 'open' else status end
  where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists touch_chat_on_message on public.chat_messages;
create trigger touch_chat_on_message
after insert on public.chat_messages
for each row execute function public.touch_chat_conversation();

create or replace function public.welcome_new_chat()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.chat_messages(conversation_id, sender, body)
  values (new.id, 'company', '¡Hola! Somos TaskForce. Contanos qué trabajo necesitás y en qué zona.');
  return new;
end;
$$;

drop trigger if exists welcome_new_chat_trigger on public.chat_conversations;
create trigger welcome_new_chat_trigger
after insert on public.chat_conversations
for each row execute function public.welcome_new_chat();

alter table public.chat_conversations replica identity full;
alter table public.chat_messages replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.chat_conversations;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;
